name: Update Counter

on:
  repository_dispatch:
    types: [increment-counter]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update counter
        run: |
          FILE="addon/train/counter.json"
          KEY="train-addon"

          VALUE=$(jq -r ".\"$KEY\"" $FILE)
          NEW_VALUE=$((VALUE + 1))

          jq ".\"$KEY\" = $NEW_VALUE" $FILE > tmp.json
          mv tmp.json $FILE

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update counter"
